FROM registry.gitlab.com/rust_musl_docker/image:stable-latest as builder
WORKDIR /workdir
COPY . .

RUN echo "[source.crates-io]" > /root/.cargo/config \
    && echo "replace-with = 'tuna'" >> /root/.cargo/config \
    && echo "[source.tuna]" >> /root/.cargo/config \
    && echo 'registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"' >> /root/.cargo/config

RUN cargo build -j4 --release --target=x86_64-unknown-linux-musl
RUN cargo install -j4 diesel_cli --target=x86_64-unknown-linux-musl --no-default-features --features postgres

ADD https://baseone-dev.pek3b.qingstor.com/static/wait-for /wait-for
ADD https://baseone-dev.pek3b.qingstor.com/static/tini-static /tini
RUN chmod +x /tini /wait-for

FROM alpine
COPY --from=builder /workdir/target/x86_64-unknown-linux-musl/release/atom /app/atom
COPY --from=builder /workdir/migrations /app/migrations
COPY --from=builder /tini /tini
COPY --from=builder /wait-for /wait-for
COPY --from=builder /root/.cargo/bin/diesel /bin/diesel
ENTRYPOINT ["/tini", "--"]

WORKDIR /app
CMD ["/app/atom", "syncserver"]
