version: '3.3'

services:
  atom:
    image: ${ATOM_IMAGE}
    env_file:
      - .env
    volumes:
      - ./Settings.toml:/app/Settings.toml
    depends_on:
      - postgres
    command: sh -c "
        /wait-for postgres:5432 -- diesel migration run
        && /app/atom syncserver
      "
    restart: always

  web:
    image: ${ATOM_IMAGE}
    env_file:
      - .env
    volumes:
      - ./Settings.toml:/app/Settings.toml
    depends_on:
      - postgres
    command: sh -c "
        /wait-for postgres:5432 -- diesel migration run
        && /app/atom web
      "
    ports:
      - ${BIND_PORT}:${BIND_PORT}
    restart: always

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./atom-postgres:/var/lib/postgresql/data
    restart: always
